### ISSUE TITLE
quot.gui.SpotViewer error

### ISSUE THREAD

**Issue by vinsfan368** [alecheckert/quot#3]
Clicking on "Spot Viewer" in quot main results in AttributeError: PySide2.QtWidgets.QGridLayout.addWidget(): unsupported keyword 'rowSpan'. Lazy fix is to delete this parameter from line 208 of spotViewer.py.

Notably, my conda environment has pyqtgraph=0.12.4=pyhd8ed1ab_0 and 
pyside2=5.15.6=py37h8675123_2, which is different from the spec'd quot_env, but this is the only way I (and others in the lab with M1 Macs) could get conda to install these packages (maybe because lower versions are missing wheels for the new M1 architecture).

**Comment by alecheckert** [comment]
I think it's worth updating to a PySide6-based environment; I've had more success with that for other projects on M1.

**Comment by vinsfan368** [comment]
I think we've confirmed that the quot_env_v2 works across multiple OS. Close @alecheckert?

**Comment by alecheckert** [comment]
Sounds good - closing.
